version: "3.9"

services:
  nginx:
    image: nginx 
    deploy:
      replicas: 3
    ports:
      - "8024:80"
  redis:
    image: redis:alpine
  tomcat: 
    image: tomcat:9.0
    deploy:
      replicas: 3 
    ports:
      - "8080:8080"
